### PR TITLE
Fix location state (#394)

### LINKED ISSUE #394: V6.7.0 breaks the location state flow
Hi, I tried to update to v6.7.0 and I found out that it breaks the flow of the app (maybe most of the apps that use this will get this issue also). It's caused by the inclusion of location's `state` into the payload of the redux action, thus it's causing the app to be re-rendered multiple times and also resulting in pushing too many stacks into the browser history.

> history.push({
        pathname: '/other-page',
        state: responseData,
      });

if state is not passed, then it works as normal. Maybe someone could come up with a solution for this? In the meantime, I revert back to version prior to v6.7.0

Thanks!

### PR DESCRIPTION
**Pull request by BlazPocrnja**
Closes #394. This change deep compares location state objects to prevent incorrectly pushing to history multiple times when state is changed.

- [x] Ran all tests

### CODE REVIEW

File: src/ConnectedRouter.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import React, { PureComponent } from 'react'
 import PropTypes from 'prop-types'
 import { connect, ReactReduxContext } from 'react-redux'
 import { Router } from 'react-router'
+import { isEqual } from 'lodash'
```
Comment (supasate) [inline src/ConnectedRouter.js]: `import isEqual from 'lodash.isequal'` to avoid loading the whole lodash module. 

Please run `yarn add -P lodash.isequal` to update package.json and yarn.lock as peerDependencies.

**Comment by supasate** [comment]
Hi @BlazPocrnja , would you mind adding a unit test for this behavior?

**Comment by BlazPocrnja** [comment]
@supasate I added unit tests and changed the lodash function to isEqualWith to allow for custom comparator function as per this comment https://github.com/supasate/connected-react-router/issues/394#issuecomment-597730704.

File: src/ConnectedRouter.js [hunk 2]
```diff
@@ -37,15 +38,15 @@ const createConnectedRouter = (structure) => {
           search: searchInHistory,
           hash: hashInHistory,
           state: stateInHistory,
-        } = history.location
+				} = history.location
```
Comment (supasate) [inline src/ConnectedRouter.js]: nit: use spaces, not tabs.

File: src/ConnectedRouter.js [hunk 3]
```diff
@@ -104,7 +105,8 @@ const createConnectedRouter = (structure) => {
     }).isRequired,
     basename: PropTypes.string,
     children: PropTypes.oneOfType([ PropTypes.func, PropTypes.node ]),
-    onLocationChanged: PropTypes.func.isRequired,
+		onLocationChanged: PropTypes.func.isRequired,
```
Comment (supasate) [inline src/ConnectedRouter.js]: ditto: spaces

File: src/ConnectedRouter.js [hunk 4]
```diff
@@ -104,7 +105,8 @@ const createConnectedRouter = (structure) => {
...
+		stateCompareFunction: PropTypes.func,
```
Comment (supasate) [inline src/ConnectedRouter.js]: ditto: spaces

File: src/ConnectedRouter.js [hunk 5]
```diff
@@ -18,7 +19,7 @@ const createConnectedRouter = (structure) => {
     constructor(props) {
       super(props)
 
-      const { store, history, onLocationChanged } = props
+      const { store, history, onLocationChanged, stateCompareFunction} = props
```
Comment (supasate) [inline src/ConnectedRouter.js]: nit: add a space before the closing curling brace.

File: test/ConnectedRouter.test.js [hunk 6]
```diff
@@ -135,6 +135,126 @@ describe('ConnectedRouter', () => {
...
+        payload: {
+          location: {
+            pathname: '/',
+            search: '',
+            hash: '',
+            state: { foo: 'bar' }
+          },
+          action: 'PUSH',
+        }
+			})
```
Comment (supasate) [inline test/ConnectedRouter.test.js]: ditto: spaces

File: test/ConnectedRouter.test.js [hunk 7]
```diff
@@ -135,6 +135,126 @@ describe('ConnectedRouter', () => {
...
+			
+			expect(props.history.entries).toHaveLength(3)
```
Comment (supasate) [inline test/ConnectedRouter.test.js]: ditto: spaces

File: test/ConnectedRouter.test.js [hunk 8]
```diff
@@ -135,6 +135,126 @@ describe('ConnectedRouter', () => {
...
```
Comment (supasate) [inline test/ConnectedRouter.test.js]: ditto

File: test/ConnectedRouter.test.js (hunk 7 above)
Comment (supasate) [inline test/ConnectedRouter.test.js]: ditto: spaces

File: test/ConnectedRouter.test.js [hunk 9]
```diff
@@ -135,6 +135,126 @@ describe('ConnectedRouter', () => {
...
+            search: '',
+            hash: '',
+            state: { foo: 'baz' }
+          },
+          action: 'PUSH',
+        }
+      })
+
+      expect(props.history.entries).toHaveLength(4)
+    })
```
Comment (supasate) [inline test/ConnectedRouter.test.js]: Can you split this into another test? So, we have one for testing that it doesn't update if the location state structure doesn't change, and another one for testing that it updates if the location state structure changes.

File: test/ConnectedRouter.test.js [hunk 10]
```diff
@@ -135,6 +135,126 @@ describe('ConnectedRouter', () => {
...
+        payload: {
+          location: {
+            pathname: '/',
+            search: '',
+            hash: '',
+            state: { foo: 'bar' }
+          },
+          action: 'PUSH',
+        }
+			})
```
Comment (supasate) [inline test/ConnectedRouter.test.js]: ditto

File: test/ConnectedRouter.test.js [hunk 11]
```diff
@@ -135,6 +135,126 @@ describe('ConnectedRouter', () => {
...
+      )
+      
+      mount(
+        <Provider store={store}>
+          <ConnectedRouter
+            stateCompareFunction={(a, b) => {
+							return a === undefined  || (a.foo === "baz" && b.foo === 'bar') ? true : false
+            }}
+            {...props}
+					>
```
Comment (supasate) [inline test/ConnectedRouter.test.js]: ditto

File: test/ConnectedRouter.test.js [hunk 12]
```diff
@@ -135,6 +135,126 @@ describe('ConnectedRouter', () => {
...
+          router: connectRouter(props.history)
+        }),
+        compose(applyMiddleware(routerMiddleware(props.history)))
+      )
+      
+      mount(
+        <Provider store={store}>
+          <ConnectedRouter
+            stateCompareFunction={(a, b) => {
+							return a === undefined  || (a.foo === "baz" && b.foo === 'bar') ? true : false
```
Comment (supasate) [inline test/ConnectedRouter.test.js]: No need to add `a === undefined` which we doesn't test it. Only the second comparison is enough to test this comparison feature.

```suggestion
              return (a.foo === 'baz' && b.foo === 'bar') ? true : false
```

**Comment by BlazPocrnja** [comment]
@supasate Sorry for the delay! I made the changes you requested. Except when testing the custom state comparator function, there needs to be a check when the state's are undefined (which is the case when you first push to history, or the store). I rewrote the test to make it a bit clearer. It's rebased now too!

**Comment by supasate** [comment]
LGTM. Thanks for your contribution @BlazPocrnja !

**Comment by supasate** [comment]
I just noticed that it breaks the test because lodash.isequalwith is not listed in devDependencies. (https://travis-ci.org/github/supasate/connected-react-router/builds/665324580?utm_medium=notification&utm_source=github_status). I'm not sure why Travis didn't show up here. I'm fixing in #408.

**Comment by BlazPocrnja** [comment]
My apologies! Looks like it's passing now, so that's a relief. Thanks!
